# Generated by Django 6.0.4 on 2026-04-20 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbiter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Synthesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('plan', 'Pre-conference session plan'), ('preliminary', 'Preliminary board recommendation'), ('final', 'Final board recommendation')], max_length=20)),
                ('content', models.JSONField()),
                ('edited_content', models.JSONField(blank=True, null=True)),
                ('model_used', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syntheses', to='arbiter.attendee')),
                ('cites', models.ManyToManyField(blank=True, related_name='cited_by', to='arbiter.attendancelog')),
            ],
            options={
                'verbose_name_plural': 'Syntheses',
                'ordering': ['-created_at'],
            },
        ),
    ]
