# Generated by Django 6.0.4 on 2026-04-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbiter', '0002_synthesis'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='tension_notes',
            field=models.TextField(blank=True),
        ),
    ]
