# Generated by Django 6.0.4 on 2026-04-28 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbiter', '0003_attendancelog_tension_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='non_session_time_budget',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VendorVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('tension_notes', models.TextField(blank=True)),
                ('contradiction_flagged', models.BooleanField(default=False)),
                ('contradiction_notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_visits', to='arbiter.attendee')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
