# Generated by Django 6.0.4 on 2026-04-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbiter', '0004_attendee_non_session_time_budget_vendorvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='synthesis',
            name='edited_text',
            field=models.TextField(blank=True),
        ),
    ]
