# Author: Ian Sun | isun@bu.edu
# Description: Parses the SecureWorld Boston 2026 agenda HTML into structured
# session records for seeding the Arbiter database. Walks the conference's
# day-and-session DOM layout with BeautifulSoup, pulls title / speaker / time
# / description out of each session node, and infers a short topic_area label
# from the title and description text.

# generated by Claude Code for easy rendering of secureworld agenda. not general purpose!

from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import date, datetime, time
from typing import Iterator
from zoneinfo import ZoneInfo

from bs4 import BeautifulSoup, Tag


# SecureWorld Boston runs in Eastern time. Storing the parsed datetimes as
# America/New_York (rather than naive wall-clock values) means the data stays
# correct regardless of the Django project's TIME_ZONE setting.
CONFERENCE_TZ = ZoneInfo("America/New_York")


# Keyword-to-topic rules evaluated in priority order; first match wins. More
# specific topics (AI, Zero Trust, Identity) are listed before catch-alls
# (Compliance, Governance, Leadership) so a session that touches both still
# gets its most distinctive label. Each keyword is matched as a substring
# against the lowercased " title + description " haystack, with leading and
# trailing spaces around the haystack so rules ending in a space can match
# at the start or end of the text.
_TOPIC_RULES: list[tuple[str, tuple[str, ...]]] = [
    ("AI", (
        "artificial intelligence", "machine learning", "llm", "generative",
        "genai", "chatgpt", "copilot", " ai ", " ai-", "ai/", "agentic",
    )),
    ("Zero Trust", ("zero trust", "zta")),
    ("Identity", (
        "identity", "iam ", "iga", "authentication", "mfa", "sso ",
        "privileged access", "pam ",
    )),
    ("Cloud Security", (
        "cloud", "aws ", "azure", "gcp ", "saas", "iaas", "multi-cloud",
        "hybrid cloud",
    )),
    ("Threat Intelligence", (
        "threat intelligence", "threat actor", "apt ", "adversar",
        "dark web", "nation-state", "nation state",
    )),
    ("Incident Response", (
        "incident response", "ransomware", "malware", "breach",
        "security operations", "soc ", "forensic",
    )),
    ("Vulnerability Management", (
        "vulnerability", "patch management", "cve ", "exploit",
    )),
    ("Supply Chain", (
        "supply chain", "third-party", "third party risk", "vendor risk",
    )),
    ("Privacy", ("privacy", "gdpr", "ccpa", "data protection")),
    ("Compliance", (
        "compliance", "regulation", "regulator", "hipaa", "pci-dss",
        "pci dss", "sox ", "nist ", "iso 27",
    )),
    ("Governance", (
        "governance", "grc ", "risk management", "board ", "audit",
    )),
    ("Leadership", (
        "ciso", "leadership", "career", "communication skills",
        "women in", "diversity", "culture",
    )),
    ("OT/IoT", (
        "ot security", "iot", "ics ", "operational technology", "scada",
    )),
]


# Matches the first "hh:mm am|pm" token in a session-time string. The
# accordion copy reads like "7:30 am - 9:00 am"; the first match is the
# start time, which is what we store on Session.time_slot.
_TIME_RE = re.compile(r"\b(\d{1,2}):(\d{2})\s*(am|pm)\b", re.IGNORECASE)


@dataclass
class ParsedSession:
    """One session extracted from the agenda HTML. Captures only the fields
    that map onto the Arbiter Session model, not the full SecureWorld record
    (registration level, location, speaker photo, etc. are dropped)."""

    title: str
    speaker: str
    topic_area: str
    time_slot: datetime
    description: str


def infer_topic_area(title: str, description: str) -> str:
    """Infer a short topic-area label for a session from its title and
    description text.

    Args:
        title: the session title as parsed from .session-title.
        description: the session description text (may be empty).

    Returns:
        A short label like "AI", "Identity", "Compliance". Falls back to
        "General" when no rule matches — typical for logistics sessions such
        as registration, meals, and networking hall hours, which legitimately
        have no technical topic.
    """
    haystack = f" {title} {description} ".lower()
    for label, keywords in _TOPIC_RULES:
        for keyword in keywords:
            if keyword in haystack:
                return label
    return "General"


def _parse_day_title(text: str) -> date:
    """Parse a session-day header string into a date.

    Args:
        text: the raw .session-day-title text, e.g. "Wednesday, April 8, 2026".

    Returns:
        A datetime.date matching the parsed day.

    Raises:
        ValueError: if the string does not match the expected format, so the
            caller can skip malformed day blocks rather than abort the parse.
    """
    cleaned = text.strip().rstrip(",").strip()
    return datetime.strptime(cleaned, "%A, %B %d, %Y").date()


def _parse_start_time(text: str) -> time:
    """Extract the first hh:mm am/pm token from a session-time string and
    return it as a naive time.

    Args:
        text: a session-time string, either a single time ("7:30 am") or a
            range ("7:30 am - 9:00 am"). The leading token is always the
            start time, which is what we want.

    Returns:
        A naive datetime.time representing the start of the session.

    Raises:
        ValueError: if no recognizable time token is present.
    """
    match = _TIME_RE.search(text)
    if not match:
        raise ValueError(f"no time found in {text!r}")
    hour_str, minute_str, meridiem = match.groups()
    hour = int(hour_str) % 12
    if meridiem.lower() == "pm":
        hour += 12
    return time(hour=hour, minute=int(minute_str))


def _extract_text(tag: Tag | None, separator: str = " ") -> str:
    """Return a stripped text extract of a BeautifulSoup tag, or the empty
    string when the tag is missing.

    Args:
        tag: the BeautifulSoup Tag to extract text from, or None.
        separator: the string inserted between adjacent block children so
            their text does not run together. Defaults to a single space;
            callers that want paragraph breaks (e.g. for .description) pass
            a double newline.

    Returns:
        The tag's rendered text content, stripped of leading and trailing
        whitespace, or the empty string if tag is None.
    """
    if tag is None:
        return ""
    return tag.get_text(separator=separator, strip=True)


def _extract_speaker(session_tag: Tag) -> str:
    """Return a one-line speaker label for a session combining the speaker's
    name with their title and company.

    Args:
        session_tag: the div.session element being parsed.

    Returns:
        A string like "Larry Wilson, CISSP — Sr. Consultant, Wilson Cyber".
        Returns the empty string when no speaker block is present, which is
        the common case for logistics sessions (registration, meals) and for
        panels whose participants are listed elsewhere on the page.
    """
    name = _extract_text(session_tag.select_one(".speaker-block .name"))
    title = _extract_text(session_tag.select_one(".speaker-block .title-company"))
    if name and title:
        return f"{name} \u2014 {title}"
    return name or title


def _iter_sessions(day_tag: Tag) -> Iterator[Tag]:
    """Yield each session div inside a given session-day container, in the
    order they appear on the page.

    Args:
        day_tag: the li.session-day element wrapping one day's agenda.

    Yields:
        Each div.session that is a direct child of .sessions-container within
        this day block. Using the direct-child combinator avoids accidentally
        picking up nested .session class matches elsewhere in the DOM.
    """
    container = day_tag.select_one(".sessions-container")
    if container is None:
        return
    yield from container.select(".sessions-container > .session")


def parse_sessions(html: str) -> list[ParsedSession]:
    """Parse the SecureWorld agenda HTML and return all sessions found.

    Args:
        html: the full HTML source of the agenda page.

    Returns:
        A list of ParsedSession records in document order. Sessions whose
        day header, title, or start time cannot be parsed are skipped
        silently — the source HTML occasionally contains placeholder or
        hidden nodes that carry no usable information, and aborting the
        whole parse over one bad node would be unhelpful.
    """
    soup = BeautifulSoup(html, "html.parser")
    results: list[ParsedSession] = []

    for day_tag in soup.select("li.session-day"):
        day_title_text = _extract_text(day_tag.select_one(".session-day-title"))
        try:
            day = _parse_day_title(day_title_text)
        except ValueError:
            continue

        # The sessions-container's direct children are the session nodes.
        container = day_tag.select_one(".sessions-container")
        if container is None:
            continue

        for session_tag in container.find_all(
            "div", class_="session", recursive=False
        ):
            title = _extract_text(session_tag.select_one(".session-title"))
            if not title:
                continue

            # The accordion copy carries the full range ("7:30 am - 9:00 am").
            # Fall back to the outer short time when the accordion is absent,
            # which happens for a handful of abbreviated logistics blocks.
            time_text = _extract_text(
                session_tag.select_one(".session-accordion .session-time")
            ) or _extract_text(session_tag.select_one(".session-time"))
            try:
                start = _parse_start_time(time_text)
            except ValueError:
                continue

            description = _extract_text(
                session_tag.select_one(".session-accordion .description"),
                separator="\n\n",
            )
            speaker = _extract_speaker(session_tag)
            topic_area = infer_topic_area(title, description)

            time_slot = datetime.combine(day, start).replace(
                tzinfo=CONFERENCE_TZ
            )

            results.append(ParsedSession(
                title=title,
                speaker=speaker,
                topic_area=topic_area,
                time_slot=time_slot,
                description=description,
            ))

    return results
